import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import "./theme-config.css";

import { Container, Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="space-x-5">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="violet">
          <AuthProvider>
            <NavBar />
            <main>
              <Container>{children}</Container>
            </main>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
